name: OnPullRequest

on:
  pull_request:

permissions: read-all

jobs:
  security-file-check:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Check Security.md file
        run: |
          if [ ! -f ./Security.md ]; then
            echo "Security.md file is missing"
            exit 1
          fi

  version-check:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: version-check
        run: |
          /bin/bash version-check.sh
          if [[ $? -eq 1 ]]; then
            echo "version check failed"
            exit 1
          fi

  build-test-scan:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: "1.23"

      - name: Style Checker
        run: |
          gofmt -l .
          if [[ $(gofmt -l . | wc -l) -gt 0 ]]; then
             echo "Atleast 1 file need formatting"
             exit 1
          fi

      - name: Unit Test Coverage
        run: |
          make test-coverage
          if [ $? -ne 0 ]; then
            echo "Unit tests failed"
            exit 1
          fi
